[
  {
    "name": "Ibrahim Sheikh",
    "medical_history": "Gunshot wound",
    "injury_date": "2024-07-19",
    "age": 34,
    "gender": "Male",
    "contact_details": "8801900000009",
    "occupation": "Electric Technician",
    "blood_group": "B+",
    "current_status": "Unreachable",
    "treatment_type": "Gunshot management",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-09",
    "receiver_amount_bdt": 50000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35674D",
    "required_support": "Medicine and financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Hasan Chowdhury",
    "medical_history": "Bone fractures (both legs)",
    "injury_date": "2024-07-20",
    "age": 25,
    "gender": "Male",
    "contact_details": "8801900000010",
    "occupation": "Garments Worker",
    "blood_group": "O+",
    "current_status": "Requires financial support",
    "treatment_type": "Fracture management",
    "fund_amount_bdt": 25000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-10",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Mahmud Ali",
    "medical_history": "Bone fracture, two operations",
    "injury_date": "2024-07-18",
    "age": 14,
    "gender": "Male",
    "contact_details": "8801900000011",
    "occupation": "Student",
    "blood_group": "O+",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery (operations)",
    "fund_amount_bdt": 55000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-11",
    "receiver_amount_bdt": 55000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35675D",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Nayeem Uddin",
    "medical_history": "Bone fracture, two operations",
    "injury_date": "2024-07-19",
    "age": 22,
    "gender": "Male",
    "contact_details": "8801900000012",
    "occupation": "Delivery Man",
    "blood_group": "B+",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery (operations)",
    "fund_amount_bdt": 70000,
    "fund_status": "Declined",
    "transaction_date": "2024-12-12",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Adnan Karim",
    "medical_history": "Bone fracture, two operations; ring needed",
    "injury_date": "2024-07-21",
    "age": 21,
    "gender": "Male",
    "contact_details": "8801900000013",
    "occupation": "Handyman",
    "blood_group": "B+",
    "current_status": "Needs blood, support",
    "treatment_type": "Surgery, ring application",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-13",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Tamim Iqbal",
    "medical_history": "Hip fractured",
    "injury_date": "2024-07-18",
    "age": 18,
    "gender": "Male",
    "contact_details": "8801900000014",
    "occupation": "Student",
    "blood_group": "O+",
    "current_status": "Released",
    "treatment_type": "Hip surgery (plate)",
    "fund_amount_bdt": 40000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-14",
    "receiver_amount_bdt": 40000,
    "transaction_methods": "Cash",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Zayan Rahman",
    "medical_history": "Hip surgery (plate needed)",
    "injury_date": "2024-07-21",
    "age": 23,
    "gender": "Male",
    "contact_details": "8801900000015",
    "occupation": "Salesman",
    "blood_group": "A+",
    "current_status": "Wrong number",
    "treatment_type": "Surgery",
    "fund_amount_bdt": 45000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-15",
    "receiver_amount_bdt": 45000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35676D",
    "required_support": "Medicine and financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Fahim Anwar",
    "medical_history": "Two toes amputated, infected",
    "injury_date": "2024-07-18",
    "age": 21,
    "gender": "Male",
    "contact_details": "8801900000016",
    "occupation": "Bank Peon",
    "blood_group": "A+",
    "current_status": "Switched off",
    "treatment_type": "Amputation, infection treatment",
    "fund_amount_bdt": 55000,
    "fund_status": "Declined",
    "transaction_date": "2024-12-16",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Medicine and financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },

  {
    "name": "Farhan Siddiqui",
    "medical_history": "Gunshot, bullet removed",
    "injury_date": "2024-08-04",
    "age": 46,
    "gender": "Male",
    "contact_details": "8801900000007",
    "occupation": "Rickshaw puller",
    "blood_group": "N/A",
    "current_status": "Normal",
    "treatment_type": "Bullet removed",
    "fund_amount_bdt": 35000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-07",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Mirpur-1",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Khalid Mahmood",
    "medical_history": "Bone fracture",
    "injury_date": "2024-07-20",
    "age": 18,
    "gender": "Male",
    "contact_details": "8801900000008",
    "occupation": "Student",
    "blood_group": "A+",
    "current_status": "A+ blood needed",
    "treatment_type": "Fracture management",
    "fund_amount_bdt": 60000,
    "fund_status": "Partially Paid",
    "transaction_date": "2024-12-08",
    "receiver_amount_bdt": 30000,
    "transaction_methods": "Cash",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Ibrahim Sheikh",
    "medical_history": "Gunshot wound",
    "injury_date": "2024-07-19",
    "age": 34,
    "gender": "Male",
    "contact_details": "8801900000009",
    "occupation": "Electric Technician",
    "blood_group": "B+",
    "current_status": "Unreachable",
    "treatment_type": "Gunshot management",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-09",
    "receiver_amount_bdt": 50000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35674D",
    "required_support": "Medicine and financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Hasan Chowdhury",
    "medical_history": "Bone fractures (both legs)",
    "injury_date": "2024-07-20",
    "age": 25,
    "gender": "Male",
    "contact_details": "8801900000010",
    "occupation": "Garments Worker",
    "blood_group": "O+",
    "current_status": "Requires financial support",
    "treatment_type": "Fracture management",
    "fund_amount_bdt": 25000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-10",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Mahmud Ali",
    "medical_history": "Bone fracture, two operations",
    "injury_date": "2024-07-18",
    "age": 14,
    "gender": "Male",
    "contact_details": "8801900000011",
    "occupation": "Student",
    "blood_group": "O+",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery (operations)",
    "fund_amount_bdt": 55000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-11",
    "receiver_amount_bdt": 55000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35675D",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Nayeem Uddin",
    "medical_history": "Bone fracture, two operations",
    "injury_date": "2024-07-19",
    "age": 22,
    "gender": "Male",
    "contact_details": "8801900000012",
    "occupation": "Delivery Man",
    "blood_group": "B+",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery (operations)",
    "fund_amount_bdt": 70000,
    "fund_status": "Declined",
    "transaction_date": "2024-12-12",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Adnan Karim",
    "medical_history": "Bone fracture, two operations; ring needed",
    "injury_date": "2024-07-21",
    "age": 21,
    "gender": "Male",
    "contact_details": "8801900000013",
    "occupation": "Handyman",
    "blood_group": "B+",
    "current_status": "Needs blood, support",
    "treatment_type": "Surgery, ring application",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-13",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Tamim Iqbal",
    "medical_history": "Hip fractured",
    "injury_date": "2024-07-18",
    "age": 18,
    "gender": "Male",
    "contact_details": "8801900000014",
    "occupation": "Student",
    "blood_group": "O+",
    "current_status": "Released",
    "treatment_type": "Hip surgery (plate)",
    "fund_amount_bdt": 40000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-14",
    "receiver_amount_bdt": 40000,
    "transaction_methods": "Cash",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },

  {
    "name": "Zayan Rahman",
    "medical_history": "Hip surgery (plate needed)",
    "injury_date": "2024-07-21",
    "age": 23,
    "gender": "Male",
    "contact_details": "8801900000015",
    "occupation": "Salesman",
    "blood_group": "A+",
    "current_status": "Wrong number",
    "treatment_type": "Surgery",
    "fund_amount_bdt": 45000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-15",
    "receiver_amount_bdt": 45000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35676D",
    "required_support": "Medicine and financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Fahim Anwar",
    "medical_history": "Two toes amputated, infected",
    "injury_date": "2024-07-18",
    "age": 21,
    "gender": "Male",
    "contact_details": "8801900000016",
    "occupation": "Bank Peon",
    "blood_group": "A+",
    "current_status": "Switched off",
    "treatment_type": "Amputation, infection treatment",
    "fund_amount_bdt": 55000,
    "fund_status": "Declined",
    "transaction_date": "2024-12-16",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Medicine and financial support",
    "incident_spot": "Confidential",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Ashraf Islam",
    "medical_history": "Leg amputated",
    "injury_date": "2024-08-05",
    "age": 29,
    "gender": "Male",
    "contact_details": "8801900000017",
    "occupation": "Madrasa Teacher",
    "blood_group": "B+",
    "current_status": "Under treatment",
    "treatment_type": "Amputation",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-17",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Medicine and financial support",
    "incident_spot": "Jatrabari",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Haris Ahmed",
    "medical_history": "Gunshot wound; leg bone broken",
    "injury_date": "2024-08-03",
    "age": 40,
    "gender": "Male",
    "contact_details": "8801900000018",
    "occupation": "Day Laborer",
    "blood_group": "O+",
    "current_status": "Surgery on 11 August",
    "treatment_type": "Bone fracture and wound management",
    "fund_amount_bdt": 30000,
    "fund_status": "Partially Paid",
    "transaction_date": "2024-12-18",
    "receiver_amount_bdt": 15000,
    "transaction_methods": "Cash",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Kachpur",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Reza Sharif",
    "medical_history": "Gunshot wound; leg amputated",
    "injury_date": "2024-07-18",
    "age": 23,
    "gender": "Male",
    "contact_details": "8801900000019",
    "occupation": "Private Car Driver",
    "blood_group": "A+",
    "current_status": "Financial support needed",
    "treatment_type": "Amputation",
    "fund_amount_bdt": 20000,
    "fund_status": "Approved",
    "transaction_date": "2024-12-19",
    "receiver_amount_bdt": 20000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35677D",
    "required_support": "Financial and rehab support",
    "incident_spot": "Uttara, Sector-07",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Sufyan Karim",
    "medical_history": "Gunshot at left leg, multiple fractures",
    "injury_date": "2024-07-19",
    "age": 27,
    "gender": "Male",
    "contact_details": "8801900000020",
    "occupation": "Student (Titumir Govt. College)",
    "blood_group": "A+",
    "current_status": "Normal",
    "treatment_type": "Fracture management",
    "fund_amount_bdt": 35000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-20",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "BRAC University",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Akash Farooq",
    "medical_history": "Gunshot at right hand; three operations",
    "injury_date": "2024-07-20",
    "age": 26,
    "gender": "Male",
    "contact_details": "8801900000021",
    "occupation": "Student",
    "blood_group": "B+",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery (operations)",
    "fund_amount_bdt": 60000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-21",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Rampura TV Centre",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },

  {
    "name": "Raihan Mahmud",
    "medical_history": "Gunshot wound at right leg; one operation done, another due",
    "injury_date": "Mirpur-10",
    "age": 23,
    "gender": "Male",
    "contact_details": "8801900000022",
    "occupation": "Security Guard",
    "blood_group": "O+",
    "current_status": "Normal",
    "treatment_type": "Surgery (operation ongoing)",
    "fund_amount_bdt": 40000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-22",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Father dead, mother temporary job",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Shakib Hossain",
    "medical_history": "Gunshot wound at right leg",
    "injury_date": "2024-07-19",
    "age": 30,
    "gender": "Male",
    "contact_details": "8801900000023",
    "occupation": "Store Worker",
    "blood_group": "A+",
    "current_status": "Normal",
    "treatment_type": "Wound management",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-23",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Shanir Akhra, Jatrabari",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Tanvir Rahman",
    "medical_history": "Gunshot wound at right leg; one operation done, another due",
    "injury_date": "2024-07-19",
    "age": 20,
    "gender": "Male",
    "contact_details": "8801900000024",
    "occupation": "Workshop Labor",
    "blood_group": "A+",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery (operation ongoing)",
    "fund_amount_bdt": 45000,
    "fund_status": "Partially Paid",
    "transaction_date": "2024-12-24",
    "receiver_amount_bdt": 25000,
    "transaction_methods": "Cash",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Press Club",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Shohan Karim",
    "medical_history": "Gunshot wound at left leg; severely damaged bones",
    "injury_date": "2024-07-19",
    "age": 22,
    "gender": "Male",
    "contact_details": "8801900000025",
    "occupation": "Student",
    "blood_group": "N/A",
    "current_status": "Needs financial support",
    "treatment_type": "Surgery and bone fracture management",
    "fund_amount_bdt": 60000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-25",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Rangpur",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Imtiaz Ahmed",
    "medical_history": "Gunshot wound at right leg; bone broken",
    "injury_date": "2024-07-19",
    "age": 29,
    "gender": "Male",
    "contact_details": "8801900000026",
    "occupation": "Medicine Business",
    "blood_group": "A-",
    "current_status": "Normal",
    "treatment_type": "Surgery and fracture management",
    "fund_amount_bdt": 50000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-26",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Banasree, Rampura",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Parvez Ali",
    "medical_history": "Gunshot wound at left leg; bone broken",
    "injury_date": "2024-07-19",
    "age": 26,
    "gender": "Male",
    "contact_details": "8801900000027",
    "occupation": "Rickshaw Puller",
    "blood_group": "O+",
    "current_status": "Needs financial support",
    "treatment_type": "Eye injury, residue removal",
    "fund_amount_bdt": 30000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-27",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Shanir Akhra, Jatrabari",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Tareq Anwar",
    "medical_history": "Got hit by a rubber bullet in the right eye. One residue remains inside.",
    "injury_date": "2024-08-03",
    "age": 38,
    "gender": "Male",
    "contact_details": "8801900000028",
    "occupation": "Workshop Labor",
    "blood_group": "O+",
    "current_status": "Under observation for surgery",
    "treatment_type": "Eye and head injury management",
    "fund_amount_bdt": 25000,
    "fund_status": "Pending",
    "transaction_date": "2024-12-28",
    "receiver_amount_bdt": 0,
    "transaction_methods": "Empty",
    "transaction_id": "Empty",
    "required_support": "Financial support",
    "incident_spot": "Gazipur",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  },
  {
    "name": "Jawad Hasan",
    "medical_history": "Police shot both eyes; hit on the head with a tear shell round.",
    "injury_date": "2024-08-05",
    "age": 25,
    "gender": "Male",
    "contact_details": "8801900000029",
    "occupation": "Rickshaw Puller",
    "blood_group": "N/A",
    "current_status": "Can't see with left eye; blurry vision in right; under observation.",
    "treatment_type": "Head and eye injury management",
    "fund_amount_bdt": 40000,
    "fund_status": "Partially Paid",
    "transaction_date": "2024-12-29",
    "receiver_amount_bdt": 25000,
    "transaction_methods": "Bank Transfer",
    "transaction_id": "93DJ2231ADD35679D",
    "required_support": "Medicine and financial support",
    "incident_spot": "Mirpur 2",
    "img": "https://i.ibb.co.com/4RCJF97/a.webp"
  }
]
